
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    type: joint_trajectory_controller/JointTrajectoryController
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.25, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.25, goal: 0.1 }
      elbow_joint: { trajectory: 0.25, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.25, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.25, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.25, goal: 0.1 }
    use_sim_time: false

forward_velocity_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    
    interface_name: 
      - velocity
    use_sim_time: false
forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    use_sim_time: false
# Gripper controller
rgripper_controller1:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.002
    max_effort: 100.0
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    use_sim_time: false